TRAIN_DEFAULTS = {
    "nickname": "",
    "optim.ema_decay": 0.999,
    "train.mixed_precision": True,
    "train.structure_every_steps": 100,
    "model.critic.pyramid_min_size": 16,
    "conditioning.height_enabled": False,
    "model.gradient_checkpointing": True,
    "model.generator.embedding_channels": 128,
    "model.generator.latent_channels": 64,
    "model.diffusion.beta_min": 0.1,
    "model.diffusion.beta_max": 20.0,
    "model.diffusion.time_embedding": "index",
    "conditioning.domain_keep_probability": 0.8,
    "loss.critic_local_weight": 0.5,
    "loss.r1_every_steps": 16,
    "loss.r2_weight": 0.0,
    "optim.adam_betas": [0.5, 0.9],
    "train.num_workers": 0,
}


STAGE_DEFAULTS = {
    "low_res": {
        "model.generator.anchor_multiscale_input": True,
        "conditioning.spatial_profile.enabled": False,
        "conditioning.spatial_profile.num_bins": 16,
        "conditioning.spatial_profile.critic_enabled": False,
        "loss.spatial_profile_weight": 1.0,
        "loss.spatial_profile_gradient_weight": 0.0,
        "conditioning.dropout_probability_per_case": 0.05,
        "conditioning.anchor.start_step": 0,
        "conditioning.anchor.ramp_steps": 500,
        "conditioning.anchor.borrowed_plane_probability": 0.2,
        "conditioning.anchor.bank_capacity": 4,
        "conditioning.anchor.plane_spacing": 16,
        "loss.connectivity.start_step": 0,
        "loss.connectivity.ramp_steps": 20000,
        "loss.connectivity.windows_per_plane": 4,
        "train.initial_weights": None,
    },
    "sr": {
        "train.archive_every_steps": None,
        "loss.downsample_mse_tolerance": 0.005,
        "lr_bank.refresh_every_steps": 1000,
        "conditioning.coarse_corruption_probability": 0.5,
        "conditioning.coarse_corruption_strength": 0.2,
    },
}
